steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/appraisalai/swiftly:$REVISION_ID-vectorserver", ".", "-f", "deployment/vector_server/Dockerfile"]
  timeout: 7200s
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "gcr.io/appraisalai/swiftly:$REVISION_ID-vectorserver"]
  timeout: 3600s
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'set'
  - 'image'
  - 'deployment'
  - 'swiftly-vectorserver'
  - 'eb-appraisal-sha256=gcr.io/appraisalai/swiftly:$REVISION_ID-vectorserver'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=swiftly-cluster-api'
  timeout: 600s
timeout: 15000s

